### ISSUE TITLE
update code

### ISSUE THREAD

**Issue by jessecarterMOOSE** [jhykes/nuclide-data#1]
Hi. I find this module very handy but it is a bit out of date and I'd like to help fix that. I'm not familiar with the uncertainties module but it seems that some of the function calls here have been depreciated as of v2.1. The last commit in this repo was before the release of v2.1.

What I propose:
- [x] Update code to work with uncertainties v2.1+. Mainly just updating `ufloat` calls.
- [x] Use unittests in test_nuclide_data.py

I have the code for this ready. Will submit the first PR shortly.

**Comment by jhykes** [comment]
Thanks @jessecarterMOOSE for these improvements! I still use these scripts occasionally, but haven't done any active development in them since my grad school days. Thanks for helping to clean them up a bit.

**Comment by jessecarterMOOSE** [comment]
And thanks for developing this code @jhykes! I was looking for something simple and standalone that handles elemental and nuclide data and this was perfect.
